image: python:3

variables:
    GITHUB_PUBLIC_KEY: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

tests:
    before_script:
        - "pip install -q -r requirements.txt"

    script:
        - "nosetests"

update-github-mirror:
    stage: deploy

    before_script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$GITHUB_MIRROR_DEPLOY_KEY")
        
    only:
        - master

    script:
        - mkdir -p ~/.ssh
        - touch ~/.ssh/known_hosts
        - grep -q "$GITHUB_PUBLIC_KEY" ~/.ssh/known_hosts || echo "$GITHUB_PUBLIC_KEY" >> ~/.ssh/known_hosts
        - git push git@github.com:rereadgames/unity-hooks.git $CI_BUILD_REF:master

    when: always
