#!/usr/bin/env python3

import sys

from helpers.version import VERSION_FILE, normalize, extract_version
from helpers.metadata import Files

EXPLAIN = """\
The version of the project has changed from '{}' to '{}' (which I think is
equivalent). This looks like the project is the same version, just on a
different platform. Check that this is the case - if it isn't you must update
the hook to allow the variation and commit this change.""".replace("\n", " ")

FIX = """
You should remove the file from the commit ('git reset {0}'). You can also
ignore changes to the file in future with 'git update-index --assume-unchanged
{0}' - make sure you commit it if you actually update the project
though.""".replace("\n", " ")


if __name__ == "__main__":
    fail = False

    for file in Files.modified:
        if file.path.endswith(VERSION_FILE):
            index_version = extract_version(file.staged.content)
            head_version = extract_version(file.head.content)

            if head_version != index_version:
                if head_version == normalize(index_version):
                    print(EXPLAIN.format(head_version, index_version),
                          file=sys.stderr)
                    print(FIX.format(file.path))
                    fail = True

    if fail:
        sys.exit(1)