#!/usr/bin/env python3

import sys

import git

from helpers.version import VERSION_FILE, normalize, extract_version
from helpers.metadata import Files

if __name__ == "__main__":
    repo = git.Repo(search_parent_directories=True)

    mismatched_project_versions = set()

    for file in Files.working_directory:
        if file.path.endswith(VERSION_FILE):
            working_version = extract_version(file.working_dir.content)
            head_version = extract_version(file.head.content)

            if file.staged.exists:
                staged_version = extract_version(file.staged.content)
                if staged_version == working_version:
                    continue

            if head_version != normalize(working_version):
                mismatched_project_versions.add((working_version, head_version))

    for (working_version, head_version) in mismatched_project_versions:
        print("The version of the project has changed from '{}' to '{}' "
              "(which I think is equivalent to '{}'), but this has not been "
              "committed.".format(head_version, working_version,
                                  normalize(working_version)),
              file=sys.stderr)
        print("This could be a false positive if these are the same version "
              "for different platforms. If so, please update the hook.")

    if mismatched_project_versions:
        sys.exit(1)
