#!/usr/bin/env python3

import sys
import os

import git

from version import *


if __name__ == "__main__":
    repo = git.Repo(search_parent_directories=True)

    mismatched_project_versions = set()

    for file in repo.head.commit.diff(None):
        path = file.a_path
        if file.a_path.endswith(VERSION_FILE):
            with open(os.path.join(repo.working_dir, path)) as f:
                local_version = split_version(f.read())
            remote_version = extract_version(repo.head.commit.tree[path])

            if remote_version != normalize(local_version):
                mismatched_project_versions.add((local_version, remote_version))

    for (local, remote) in mismatched_project_versions:
        print("The version of the project has changed from '{}' to '{}' "
              "(which I think is equivalent to '{}'), but this has not been "
              "committed.".format(remote, local, normalize(local)),
              file=sys.stderr)
        print("This could be a false positive if these are the same version "
              "for different platforms. If so, please update the hook.")

    if mismatched_project_versions:
        sys.exit(1)