#!/usr/bin/env python3

import sys

from metadata import *

PROBLEM = "'{}' has been added but its asset is missing."

if __name__ == "__main__":
    fail = False

    metadata_missing_asset = added_metadata() - metadata_for(added_assets())

    for name in metadata_missing_asset:
        if not is_directory_metadata(get_staged_content_for(name)):
            print(PROBLEM.format(name), file=sys.stderr)
            fail = True

    if fail:
        sys.exit(1)

