#!/usr/bin/env python3

import sys

from metadata import *

PROBLEM = "'{}' has been added but its metadata is missing."

if __name__ == "__main__":
    fail = False

    assets_missing_metadata = added_assets() - assets_for(added_metadata())

    for name in assets_missing_metadata:
        if name not in assets_for(added_metadata_mistaken_as_rename()):
            print(PROBLEM.format(name), file=sys.stderr)
            fail = True

    if fail:
        sys.exit(1)
