#!/usr/bin/env python3

import sys

from helpers.metadata import Files

PROBLEM = "'{}' has been deleted but its metadata has not been."

if __name__ == "__main__":
    fail = False

    deleted_assets = {file for file in Files.deleted if file.is_asset}

    assets_for_deleted_metadata = \
        ({file.asset for file in Files.deleted if file.is_metadata} |
            Files.likely_missed_deleted_metadata)

    deleted_assets_with_remaining_metadata = \
        deleted_assets - assets_for_deleted_metadata

    for file in deleted_assets_with_remaining_metadata:
        print(PROBLEM.format(file.path), file=sys.stderr)
        fail = True

    if fail:
        sys.exit(1)
