#!/usr/bin/env python3

import sys

from metadata import *

PROBLEM = "'{}' has been deleted but its metadata file has not."
FIX = "To fix, delete '{0}.meta' or do not delete '{0}'."

if __name__ == "__main__":
    deleted_assets = set()
    deleted_metadata = set()

    for path, _ in staged_paths(change_type="D"):
        if path.startswith(ASSETS_DIR):
            if path.endswith(META_EXT):
                deleted_metadata.add(path[:-len(META_EXT)])
            else:
                deleted_assets.add(path)

    redundant_metadata = deleted_assets - deleted_metadata

    for path in redundant_metadata:
        print(PROBLEM.format(path), file=sys.stderr)
        print(FIX.format(path), file=sys.stderr)

    if redundant_metadata:
        sys.exit(1)
