#!/usr/bin/env python3

import sys

from metadata import *

PROBLEM = "'{}' has been deleted but its metadata has not been."

if __name__ == "__main__":
    fail = False

    deleted_assets_with_remaining_metadata = \
        deleted_assets() - assets_for(deleted_metadata())

    for name in deleted_assets_with_remaining_metadata:
        if name not in assets_for(deleted_metadata_mistaken_as_rename()):
            print(PROBLEM.format(name), file=sys.stderr)
            fail = True

    if fail:
        sys.exit(1)
