#!/usr/bin/env python3

import sys

from metadata import *

PROBLEM = "'{}' has been deleted but its asset has not been."

if __name__ == "__main__":
    fail = False

    deleted_metadata_with_remaining_asset = \
        deleted_metadata() - metadata_for(deleted_assets())

    for name in deleted_metadata_with_remaining_asset:
        if not is_directory_metadata(get_head_content_for(name)):
            print(PROBLEM.format(name), file=sys.stderr)
            fail = True

    if fail:
        sys.exit(1)
