#!/usr/bin/env python3

import sys

from helpers.metadata import Files

PROBLEM = "'{}' has been deleted but its asset has not been."

if __name__ == "__main__":
    fail = False

    deleted_metadata = {file for file in Files.deleted if file.is_metadata}

    metadata_for_deleted_assets = \
        {file.metadata for file in Files.deleted if file.is_asset}

    deleted_metadata_with_remaining_asset = \
        deleted_metadata - metadata_for_deleted_assets

    for file in deleted_metadata_with_remaining_asset:
        if not file.head.is_directory_metadata:
            print(PROBLEM.format(file.path), file=sys.stderr)
            fail = True

    if fail:
        sys.exit(1)
