#!/usr/bin/env python3

import sys

from metadata import *

PROBLEM = "'{}' has been renamed (from '{}') but its metadata has not."

if __name__ == "__main__":
    fail = False

    renamed_assets_without_renamed_metadata = \
        renamed_assets() - assets_for(renamed_metadata())

    for old_name, new_name in renamed_assets_without_renamed_metadata:
        print(PROBLEM.format(new_name, old_name), file=sys.stderr)
        fail = True

    if fail:
        sys.exit(1)
