#!/usr/bin/env python3

import sys

from helpers.metadata import Files

PROBLEM = "'{}' has been renamed (from '{}') but its asset has not."

if __name__ == "__main__":
    fail = False

    renamed_metadata = {file for file in Files.renamed if file.is_metadata}

    metadata_for_renamed_assets = \
        {file.metadata for file in Files.renamed if file.is_asset}

    renamed_metadata_without_renamed_asset = \
        renamed_metadata - metadata_for_renamed_assets

    renamed_metadata_without_renamed_asset -= \
        Files.renames_likely_to_be_different_files

    for file in renamed_metadata_without_renamed_asset:
        if not (file.staged.is_directory_metadata or
                file.renamed_from.head.is_directory_metadata):
            print(PROBLEM.format(file.path, file.renamed_from_path), file=sys.stderr)
            fail = True

    if fail:
        sys.exit(1)

