#!/usr/bin/env python3

import sys

from metadata import *

PROBLEM = "'{}' has been renamed (from '{}') but its asset has not."

if __name__ == "__main__":
    fail = False

    renamed_metadata_without_renamed_asset = \
        renamed_metadata() - metadata_for(renamed_assets())

    for old_name, new_name in renamed_metadata_without_renamed_asset:
        if (old_name, new_name) not in likely_mistaken_renames():
            print(PROBLEM.format(new_name, old_name), file=sys.stderr)
            fail = True

    if fail:
        sys.exit(1)

