#!/usr/bin/env python3

import sys

from helpers.metadata import Files

MULTIPLE_STAGED_ERROR = "Multiple files staged for '{}'."

EXPLAIN = "The guid in the metadata file '{}' has changed - most likely it " \
          "got deleted and generated again by Unity."

FIX = "You should revert it to the old version. If the old asset was deleted " \
      "and this one is different with the same name, split the deletion of " \
      "the old asset and the creation of the new one across two commits."


if __name__ == "__main__":
    fail = False

    renamed_assets = \
        {file for file in Files.renamed if file.is_asset}

    modified_metadata = \
        {file for file in Files.modified if file.is_metadata}

    changed_guids = \
        ({file.metadata for file in renamed_assets
          if file.metadata.staged.guid != file.renamed_from.metadata.head.guid} |
         {file for file in modified_metadata
          if file.staged.guid != file.head.guid})

    for file in changed_guids:
        print(EXPLAIN.format(file.path), file=sys.stderr)
        print(FIX)
        fail = True

    if fail:
        sys.exit(1)
